### ISSUE TITLE
GOPATH seems to be incorrectly setup since very recently

### ISSUE THREAD

**Issue by cmeury** [wercker/step-setup-go-workspace#12]
Our wercker builds are failing since around 30 minutes. The only difference I can see is in the `setup-go-workspace` step.

* before: `export WERCKER_SETUP_GO_WORKSPACE_GOPATH="$GOPATH"`
* now: `export WERCKER_SETUP_GO_WORKSPACE_GOPATH=\$GOPATH`

**Comment by agnihotrigaurav** [comment]
Seems there is a regression on CLI. We have rolled back to last version. 
Kindly re-execute your build.

**Comment by andriylesch** [comment]
Hello @agnihotrigaurav 
We still have the same problem, Can you check it again, please 
![screen shot 2018-06-22 at 11 35 35](https://user-images.githubusercontent.com/24546859/41769703-740d0298-7610-11e8-980a-e8fc0d9207b9.png)

**Comment by agnihotrigaurav** [comment]
There was another regression, because of which revert was not successful. Can you please try it again.

**Comment by cmeury** [comment]
Just executed two builds successfully, thanks @agnihotrigaurav

**Comment by agnihotrigaurav** [comment]
Closing issue as reporter successfully executed his build after revert.
