### ISSUE TITLE
Document usage for local imports

### ISSUE THREAD

**Issue by mwhooker** [wercker/step-setup-go-workspace#7]
This step assumes that you're using absolute import paths. If you aren't, you can set `WERCKER_SETUP_GO_WORKSPACE_PACKAGE_DIR` to be the name of your project.

For example, if your project is laid out like https://github.com/mwhooker/godemo,

then you'll want to set `WERCKER_SETUP_GO_WORKSPACE_PACKAGE_DIR` to `godemo`

**Comment by hatchan** [comment]
The convention for this step is to use [github.com|bitbucket.com]/[git owner]/[repo name].

If you want to change this path than you need to use the `package-dir` parameter, which was created just for this. This parameter will set the above mentioned environment variable.
